export const beaches = [
    {
        name: "Dunga",
        county: "Kisumu",
        lake: "Lake Victoria",
        latitude: -0.1481,
        longitude: 34.7336,
        isActive: true,
    },
    {
        name: "Usenge",
        county: "Siaya",
        lake: "Lake Victoria",
        latitude: -0.0631,
        longitude: 34.0322,
        isActive: true,
    },
    {
        name: "Kendu Bay",
        county: "Homa Bay",
        lake: "Lake Victoria",
        latitude: -0.3667,
        longitude: 34.6500,
        isActive: true,
    },
    {
        name: "Homa Bay",
        county: "Homa Bay",
        lake: "Lake Victoria",
        latitude: -0.5167,
        longitude: 34.4500,
        isActive: true,
    },
    {
        name: "Muhuru Bay",
        county: "Migori",
        lake: "Lake Victoria",
        latitude: -0.7000,
        longitude: 34.0667,
        isActive: true,
    },
];